[workspace.package]
edition = "2024"
authors = ["Andrew Ward (andy.ward.uk@gmail.com)"]

[workspace]
resolver = "2"

members = ["aoc", "day01", "day02", "day03"]

[profile.release]
debug = true
lto = true
