[package]
name = "day14vis"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../aoc", features = ["gif"] }
regex = "1.11.1"
