use aoc::input::parse_test_vec;

use super::*;

const EXAMPLE1: &str = "\
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
";

#[test]
fn test1() {
    let input = parse_test_vec(EXAMPLE1, input_transform).unwrap();
    assert_eq!(part1(&input), 14);
    assert_eq!(part2(&input), 34);
}
